Align docker-compose on make file
cloudbees/plugin-dependency-analyzer pull request #4
Opened 2018-08-25 20:00 UTC by PierreBtz

While testing #3 I used the docker-compose file and noticed two things to change.
CC @alecharp

2018-08-25 22:24 UTC, alecharp requested changes

2018-08-25 22:24 UTC, alecharp commented on docker-compose.yml
> +      - ${HOME}/.cache/cloudbees-support/plugins:/var/lib/plugin-dependency-analyzer/.cache/cloudbees-support/plugins:ro
I had the same issue in the `Makefile`, which I fixed in #2. Good catch.

2018-08-25 22:24 UTC, alecharp commented on docker-compose.yml
> +      - 7687:7687
This shouldn't be mandatory as the bolt connection is only used between the containers. 

In the end, I don't want to expose the port `7687` because we shouldn't have to use cypher to get what we want from this project.

2018-08-27 07:54 UTC, PierreBtz commented on docker-compose.yml
> +      - 7687:7687
I understand, I had to expose it to be able to connect to the DB from the neo4j UI but I guess it's a dev profile kind of requirement.

2018-08-27 08:40 UTC, alecharp commented on docker-compose.yml
> +      - 7687:7687
Yes, that's why I don't really want to put it in the `docker-compose.yml`. It's exposed in the `Makefile` script.

2018-08-28 15:53 UTC, PierreBtz commented on docker-compose.yml
> +      - 7687:7687
Removed this change from the commit

2018-08-28 15:53 UTC, PierreBtz commented
Removed the bolt port from the commit.

2018-08-29 07:26 UTC, alecharp approved these changes

2018-08-29 07:26 UTC, merged